-- Auto-generated by twvz deploy system

local SCRIPTS = {
    [101640913672688] = {
        name = "Anime Ghosts",
        url = "https://raw.githubusercontent.com/ZhangJunZ84/twvzyyds/main/animeghost.lua",
        version = "0.0.9",
    },
    [77747658251236] = {
        name = "Sailor Piece",
        url = "https://raw.githubusercontent.com/ZhangJunZ84/twvzyyds/main/sailorpiece.lua",
        version = "0.0.6",
    },
}

local placeId = game.PlaceId
local scriptInfo = SCRIPTS[placeId]

if scriptInfo then
    pcall(function()
        game:GetService("StarterGui"):SetCore("SendNotification", {
            Title = "TWVZ",
            Text = "Loading " .. scriptInfo.name .. " " .. scriptInfo.version,
            Duration = 3,
        })
    end)
    loadstring(game:HttpGet(scriptInfo.url .. "?t=" .. tostring(tick())))()
else
    pcall(function()
        game:GetService("StarterGui"):SetCore("SendNotification", {
            Title = "TWVZ",
            Text = "No script available for this game (PlaceId: " .. tostring(placeId) .. ")",
            Duration = 5,
        })
    end)
end
